apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: sle52uja8-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-d1fa424b8b.tsu1.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:6a34b751729dd0b6e8a3474d2e4f027038dc5fb4@sha256:9579970dbf851997e0e2a9b50640609149dd59b5ad71dcfa64b58e6feec32141
          name: container-image
